version = 1

[project]
name = "BlogContent"

[extension.project]
loader = "go-module"

[extension.project.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/project/workspace/cmd/provider"

[extension.project.settings]
name = "BlogContent"

[extension.document-capability]
loader = "go-module"

[extension.document-capability.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/capability/document/cmd/provider"

[extension.document-capability.settings]
review_max_lines = 300

[extension.document-markdown]
loader = "go-module"

[extension.document-markdown.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/document/markdown/cmd/provider"

[extension.document-markdown.settings]
roots = ["src/content"]

[extension.document-relations]
loader = "go-module"

[extension.document-relations.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/document/relations/content/cmd/provider"

[extension.document-relations.settings]
articles = "src/content/articles"
series = "src/content/series"
notes = "src/content/notes"
projects = "src/content/projects"

[extension.scm-capability]
loader = "go-module"

[extension.scm-capability.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/capability/scm/cmd/provider"

[extension.credential-store]
loader = "go-module"

[extension.credential-store.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/credential/file/cmd/provider"

[extension.credential]
loader = "go-module"

[extension.credential.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/credential/github/cmd/provider"

[extension.scm]
loader = "go-module"

[extension.scm.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "65c45217942ee432ff0181627a5067c502829d8f"
package = "./extensions/scm/github/cmd/provider"

[service.document-structure]
provider = "document.markdown.goldmark"

[service.document-relations]
provider = "document.relations.content"

[service.credential-store]
provider = "credential.store.file"

[service.credential]
provider = "credential.github"

[service.scm]
provider = "scm.github"
