version = 1

[project]
name = "BlogContent"

[extension.project]
loader = "go-module"

[extension.project.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/project/workspace/cmd/provider"

[extension.project.settings]
name = "BlogContent"

[extension.document-capability]
loader = "go-module"

[extension.document-capability.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/capability/document/cmd/provider"

[extension.document-markdown]
loader = "go-module"

[extension.document-markdown.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/document/markdown/cmd/provider"

[extension.document-markdown.settings]
roots = ["src/content"]

[extension.scm-capability]
loader = "go-module"

[extension.scm-capability.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/capability/scm/cmd/provider"

[extension.credential-store]
loader = "go-module"

[extension.credential-store.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/credential/file/cmd/provider"

[extension.credential]
loader = "go-module"

[extension.credential.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/credential/github/cmd/provider"

[extension.scm]
loader = "go-module"

[extension.scm.loader_config]
module = "github.com/thinkerqaq/devtool"
version = "1af157491864ca63c965c9afcd2d0dd141222ac1"
package = "./extensions/scm/github/cmd/provider"

[service.document-structure]
provider = "document.markdown.goldmark"

[service.credential-store]
provider = "credential.store.file"

[service.credential]
provider = "credential.github"

[service.scm]
provider = "scm.github"
